
export const UPDATE_PRODUCT_COLOUR = 'UPDATE_PRODUCT_COLOUR';
export const UPDATE_KEY_FRONT_MESSAGE = 'UPDATE_KEY_FRONT_MESSAGE';
export const UPDATE_KEY_BACK_MESSAGE = 'UPDATE_KEY_BACK_MESSAGE';
export const SET_PLATE_NUMBER = 'SET_PLATE_NUMBER';
export const SET_TEXT_COLOUR = 'SET_TEXT_COLOUR';